### PR TITLE
optional argument to specify not using network

### PR DESCRIPTION
**Pull request by FoamyGuy**
This change allows the `secrets.py` file to be optional with a keyword argument that defaults to True (same behavior as current). While helping someone on discord I noticed that the simpletest script crashes if the user doesn't have a valid secrets.py file, but the example itself doesn't make use of the network. 

I think it would be great if people could start playing with the display and other non-network related functionality without having to set up extra things that won't be used yet. 

Also modified the simpletest example to use this new argument so that it can run without a secrets.py file. I tested successfully on a Feather S2 TFT on CircuitPython 7.2.5

### CODE REVIEW

**Comment by makermelissa** [comment]
The main issue I see with these changes is PortalBase expects Network to be something other than None. That would need to be updated first (see https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/blob/main/adafruit_portalbase/__init__.py).

**Comment by FoamyGuy** [comment]
@makermelissa when you have a chance can you check in on this one now that the change in PortalBase is merged is this good to go?

**Comment by FoamyGuy** [comment]
@makermelissa when you have a chance can you check in on this one now that the change in PortalBase is merged is this good to go?

**Review by makermelissa — APPROVED** [review]
Looks good. Didn't test because I don't have the hardware with me.

**Review by makermelissa — CHANGES_REQUESTED** [review]
Tested, but I noticed the new parameter wasn't added to the docstring.

**Comment by FoamyGuy** [comment]
Thank you. Latest commit adds the docstring.

**Review by makermelissa — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
